/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.gob.arcom.migracion.alfresco;

/**
 * Enumeracion para manejo de tipos Mime
 * @author cherrera
 */
public enum AlfrescoMimeType 
{
    ai("application/postscript","ai"),
    aif("audio/x-aiff","aif"),
    aifc("audio/x-aiff","aifc"),
    aiff("audio/x-aiff","aiff"),
    asc("text/plain","asc"),
    atom("application/atom+xml","atom"),
    au("audio/basic","au"),
    avi("video/x-msvideo","avi"),
    bcpio("application/x-bcpio","bcpio"),
    bin("application/octet-stream","bin"),
    bmp("image/bmp","bmp"),
    cdf("application/x-netcdf","cdf"),
    cgm("image/cgm","cgm"),
    cpio("application/x-cpio","cpio"),
    cpt("application/mac-compactpro","cpt"),
//    csh("application/x-csh"),
//    css("text/css"),
//    dcr("application/x-director"),
//    dif("video/x-dv"),
//    dir("application/x-director"),
//    djv("image/vnd.djvu"),
//    djvu("image/vnd.djvu"),
     dll("application/octet-stream","dll"),
     dmg("application/octet-stream","dmg"),
//    dms("application/octet-stream"),
    doc("application/msword","doc"),
    docx("application/msword","docx"),
//    dtd("application/xml-dtd"),
//    dv("video/x-dv"),
//    dvi("application/x-dvi"),
//    dxr("application/x-director"),
//    eps("application/postscript"),
//    etx("text/x-setext"),
//    exe("application/octet-stream"),
//    ez("application/andrew-inset"),
      gif("image/gif","gif"),
//    gram("application/srgs"),
//    grxml("application/srgs+xml"),
//    gtar("application/x-gtar"),
//    hdf("application/x-hdf"),
//    hqx("application/mac-binhex40"),
      htm("text/html","htm"),
      html("text/html","html"),
//    ice("x-conference/x-cooltalk"),
      ico("image/x-icon","ico"),
//    ics("text/calendar"),
//    ief("image/ief"),
//    ifb("text/calendar"),
//    iges("model/iges"),
//    igs("model/iges"),
      jnlp("application/x-java-jnlp-file","jnlp"),
//    jp2("image/jp2"),
      jpe("image/jpeg","jpg"),
      jpeg("image/jpeg","jpg"),
      jpg("image/jpeg","jpg"),
      js("application/x-javascript","js"),
//    kar("audio/midi"),
      latex("application/x-latex","latex"),
//    lha("application/octet-stream"),
//    lzh("application/octet-stream"),
//    m3u("audio/x-mpegurl"),
//    m4a("audio/mp4a-latm"),
//    m4b("audio/mp4a-latm"),
//    m4p("audio/mp4a-latm"),
//    m4u("video/vnd.mpegurl"),
//    m4v("video/x-m4v"),
//    mac("image/x-macpaint"),
//    man("application/x-troff-man"),
//    mathml("application/mathml+xml"),
//    me("application/x-troff-me"),
//    mesh("model/mesh"),
//    mid("audio/midi"),
//    midi("audio/midi"),
//    mif("application/vnd.mif"),
      mov("video/quicktime","mov"),
      movie("video/x-sgi-movie","movie"),
//    mp2("audio/mpeg"),
//    mp3("audio/mpeg"),
//    mp4("video/mp4"),
//    mpe("video/mpeg"),
//    mpeg("video/mpeg"),
//    mpg("video/mpeg"),
//    mpga("audio/mpeg"),
//    ms("application/x-troff-ms"),
//    msh("model/mesh"),
//    mxu("video/vnd.mpegurl"),
//    nc("application/x-netcdf"),
      octetStream("application/octet-stream","octet-stream"),
//    oda("application/oda"),
      odt("application/vnd.oasis.opendocument.text","odt"),
      ods("application/vnd.oasis.opendocument.spreadsheet","ods"),
//    ogg("application/ogg"),
//    pbm("image/x-portable-bitmap"),
//    pct("image/pict"),
//    pdb("chemical/x-pdb"),
      pdf("application/pdf","pdf"),
//    pgm("image/x-portable-graymap"),
//    pgn("application/x-chess-pgn"),
      pic("image/pict","pic"),
      pict("image/pict","pict"),
      png("image/png","png"),
      pnm("image/x-portable-anymap","pnm"),
      pnt("image/x-macpaint","pnt"),
      pntg("image/x-macpaint","pntg"),
      ppm("image/x-portable-pixmap","ppm"),
      ppt("application/vnd.ms-powerpoint","ppt"),
      pptx("application/vnd.ms-powerpoint","pptx"),
//    p7m("application/x-pkcs7-mime"),
      ps("application/postscript","ps"),
//    qt("video/quicktime"),
//    qti("image/x-quicktime"),
//    qtif("image/x-quicktime"),
//    ra("audio/x-pn-realaudio"),
//    ram("audio/x-pn-realaudio"),
//    ras("image/x-cmu-raster"),
//    rdf("application/rdf+xml"),
//    rgb("image/x-rgb"),
//    rm("application/vnd.rn-realmedia"),
//    roff("application/x-troff"),
      rtf("text/rtf","rtf"),
      rtx("text/richtext","rtx"),
//    sao("text/richtext"),
//    sgm("text/sgml"),
//    sgml("text/sgml"),
      sh("application/x-sh","sh"),
//    shar("application/x-shar"),
//    silo("model/mesh"),
//    sit("application/x-stuffit"),
//    skd("application/x-koan"),
//    skm("application/x-koan"),
//    skp("application/x-koan"),
//    skt("application/x-koan"),
//    smi("application/smil"),
//    smil("application/smil"),
//    snd("audio/basic"),
      so("application/octet-stream","so"),
//    spl("application/x-futuresplash"),
//    src("application/x-wais-source"),
//    sv4cpio("application/x-sv4cpio"),
//    sv4crc("application/x-sv4crc"),
//    svg("image/svg+xml"),
//    swf("application/x-shockwave-flash"),
//    sxw("application/vnd.sun.xml.writer"),
//    t("application/x-troff"),
//    tar("application/x-tar"),
//    tcl("application/x-tcl"),
//    tex("application/x-tex"),
//    texi("application/x-texinfofileMimeType"),
//    texinfo("application/x-texinfo"),
      tif("image/tiff","tif"),
      tiff("image/tiff","tiff"),
//    tr("application/x-troff"),
//    tsv("text/tab-separated-values"),
      txt("text/plain","txt"),
//    ustar("application/x-ustar"),
//    vcd("application/x-cdlink"),
//    vrml("model/vrml"),
//    vxml("application/voicexml+xml"),
//    wav("audio/x-wav"),
//    wbmp("image/vnd.wap.wbmp"),
//    wbmxl("application/vnd.wap.wbxml"),
//    wml("text/vnd.wap.wml"),
//    wmlc("application/vnd.wap.wmlc"),
//    wmls("text/vnd.wap.wmlscript"),
//    wmlsc("application/vnd.wap.wmlscriptc"),
//    wrl("model/vrml"),
//    xbm("image/x-xbitmap"),
    xht("application/xhtml+xml","xht"),
    xhtml("application/xhtml+xml","xhtml"),
    xls("application/vnd.ms-excel","xls"),
    xlsx("application/vnd.ms-excel","xlsx"),
    xml("application/xml","xml"),
//    xpm("image/x-xpixmap"),
    xsl("application/xml","xsl"),
//    xslt("application/xslt+xml"),
//    xul("application/vnd.mozilla.xul+xml"),
//    xwd("image/x-xwindowdump"),
//    xyz("chemical/x-xyz"),
    zip("application/zip","zip");

    private String mimeType;
    private String code;

    AlfrescoMimeType(String mime, String code)
    {
        this.mimeType = mime;
        this.code = code;
    }

    public String getMimeType()
    {
        return mimeType;
    }
    
    public String getCode()
    {
       return code;
    }

}
